# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='height_field',
            new_name='height_field_image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='width_field',
            new_name='width_field_image',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field='height_field_image', upload_to=news.models.upload_location, width_field='width_field_image'),
        ),
    ]
