# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20170723_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choice_one', models.CharField(max_length=50)),
                ('choice_two', models.CharField(max_length=50)),
                ('choice_three', models.CharField(max_length=50)),
                ('answer', models.CharField(choices=[('a', 'choice_one'), ('b', 'choice_two'), ('c', 'choice_three')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Complete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('first_speaker', models.CharField(max_length=50)),
                ('second_speaker', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mistake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('replace', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='word',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='test',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Test_Part', to='study.Part'),
        ),
        migrations.AddField(
            model_name='mistake',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Test_Mistake', to='study.Test'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Test_Dialog', to='study.Test'),
        ),
        migrations.AddField(
            model_name='complete',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Test_Complete', to='study.Test'),
        ),
        migrations.AddField(
            model_name='choices',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Test_Choices', to='study.Test'),
        ),
    ]
