# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_wordbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'Situations'), (2, 'Dialog'), (3, 'Choices'), (4, 'Find the Mistake'), (5, 'Article'), (6, 'Story'), (7, 'Translation'), (8, 'Paragraph')])),
            ],
        ),
    ]
