# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_auto_20171002_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='type',
            field=models.IntegerField(choices=[(1, 'GENERAL'), (2, 'MCQ')], default=1),
        ),
        migrations.AlterField(
            model_name='test',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Test_Part', to='study.Part'),
        ),
    ]
