# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_mistake'),
        ('study', '0003_auto_20170727_1253'),
    ]

    operations = [
    ]
