# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='wait',
            field=models.BooleanField(default=False),
        ),
    ]
