# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 12:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20170723_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='unit',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 7, 23, 12, 25, 41, 213763, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
