# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 19:51
from __future__ import unicode_literals

import asks.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('replay', models.TextField(blank=True, null=True)),
                ('image_sender', models.ImageField(blank=True, height_field='height_field_image', null=True, upload_to=asks.models.upload_location, width_field='width_field_image')),
                ('image_staff', models.ImageField(blank=True, height_field='height_field_image', null=True, upload_to=asks.models.upload_location, width_field='width_field_image')),
                ('file_sender', models.FileField(blank=True, null=True, upload_to=asks.models.upload_location)),
                ('file_staff', models.FileField(blank=True, null=True, upload_to=asks.models.upload_location)),
                ('height_field_image', models.IntegerField(default=0, null=True)),
                ('width_field_image', models.IntegerField(default=0, null=True)),
                ('wait', models.BooleanField(default=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
