# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ask',
            options={'ordering': ['-updated']},
        ),
        migrations.AddField(
            model_name='ask',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
