# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 12:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asks', '0002_auto_20170723_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ask',
            old_name='reply',
            new_name='replay',
        ),
        migrations.AlterField(
            model_name='ask',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
