# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asks', '0003_auto_20171002_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
