# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 05:43
from __future__ import unicode_literals

import asks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asks', '0004_auto_20170726_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='file_sender',
            field=models.FileField(blank=True, null=True, upload_to=asks.models.upload_location),
        ),
        migrations.AlterField(
            model_name='ask',
            name='file_staff',
            field=models.FileField(blank=True, null=True, upload_to=asks.models.upload_location),
        ),
    ]
