# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asks', '0006_auto_20170726_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='height_field_image',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ask',
            name='width_field_image',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
